### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by borsodigerii** [stirante/lol-client-java-api#12]
Hi! I'm new to this, and i have a question: do  you have a reference for all of these methods in the generated package? (Like which one what is for, examples etc)
Ty for your fast answer! :)
(Sorry for my bad English)

**Comment by borsodigerii** [comment]
And i have another question plus ofr this: When the program process this row:
`if (!api.isAuthorized()){` then the error log is this: 
`Using endpoint "" which is not in the list of allowed endpoints!
If you're seeing this message while using allowed endpoint, consider opening an issue or pull request.`
Why is this happening? (I didn't edited the packages) Thank you for your help :D

**Comment by stirante** [comment]
All generated classes are made from swagger documentation, which you can see with rift explorer: https://github.com/Pupix/rift-explorer

As for the error log, I'll check it today later. It's probably a bug, but it shouldn't interfere with anything, it's only a warning.

**Comment by borsodigerii** [comment]
Okay, i'll check it out. Do i have to close this issue, or just let it open until you check for that bug?

**Comment by stirante** [comment]
Fixed in https://github.com/stirante/lol-client-java-api/commit/4326f86e3397a76b137d3cf83787fa5eeb65b629
