### ISSUE TITLE
Questions Regarding The Current League Client API

### ISSUE THREAD

**Issue by SaeronMeng** [stirante/lol-client-java-api#14]
Hi Stirante, I'm impressed by your masterpiece and have some questions about the current League Client API. I found another version at [lcu.vivide.re](http://lcu.vivide.re/) but some of whose APIs cannot be applied to Ver 10.8 (Chinese Mainland). Could you please tell me how did you find the lastest documentation?

Also, I intend to develop a plugin for LOL and have some trouble with obtaining the instant chat log ingame. Is there any API that can achieve this function?

**Comment by stirante** [comment]
Hi,

The documentation is pulled from LoL client directly. Easiest way to check the most up to date documentation is using https://github.com/Pupix/rift-explorer

As for the ingame chat log, I don't think you can do this. This API is about client before game and ingame API doesn't have this functionality.

**Comment by SaeronMeng** [comment]
> Hi,
> 
> The documentation is pulled from LoL client directly. Easiest way to check the most up to date documentation is using https://github.com/Pupix/rift-explorer
> 
> As for the ingame chat log, I don't think you can do this. This API is about client before game and ingame API doesn't have this functionality.

Got it. Thank you so much.
