### ISSUE TITLE
Perks endpoint

### ISSUE THREAD

**Issue by OlivierMary** [stirante/lol-client-java-api#17]
Hi,

I tried to use lol-perks endpoint, but got error each times:

```
            println(api.executePost("/lol-perks/v1/pages", perks))
```
got false each time

and on client logs: 

```
005764.665|  ERROR|                   Remoting| HTTP Response 400 to POST '/lol-perks/v1/pages'
```

Any idea to get more information why I got HTTP 400 ?

**Comment by stirante** [comment]
HTTP code 400 means, that the request is invalid. I don't know what `perks` variable has, so I can't really help. 

In my own project, I use it like this https://github.com/stirante/RuneChanger/blob/master/src/main/java/com/stirante/runechanger/client/Runes.java#L122

**Comment by OlivierMary** [comment]
It's good, I find why
