### ISSUE TITLE
Riot Client api question

### ISSUE THREAD

**Issue by aleksaelezovic** [stirante/lol-client-java-api#18]
As of now, I am not able to find a way to use this lib while inside Riot Client (login screen). I would like to use '/rso-auth/' to login with provided RSOPlayerCredentials data. ClientApi doesn't recognize this 'RiotClient' window as 'an open client'. 

I would like to know if there is a way to do so or if there isn't, when will it be possible?

P.S. Thanks for this awesome lib king, very nice of you!

**Comment by stirante** [comment]
This library is only for League of Legends Client. Riot Client was never supported and I doubt it will be. If you want to login with LoL client, you might want to try opening LoL client with special command line options. For example, rift explorer creates new system.yaml file with altered configuration (they add `enable_swagger` option and remove `riotclient` configuration). After that they run LoL client with option `--system-yaml-override=pathToNewConfig`. You can see it [here](https://github.com/Pupix/rift-explorer/blob/master/util.js) in 2 last functions.

**Comment by aleksaelezovic** [comment]
Oh okay, I understand! Thank you very much!
