### ISSUE TITLE
can I get a example of getting the summoner rune

### ISSUE THREAD

**Issue by SimronJ** [stirante/lol-client-java-api#19]
I do see a class called rune, runes, and runestree under pojo package. I don't how to utilize those to get the summoner runes. 

Also, does this API allow you to set the custom rune for the summoner?

**Comment by SimronJ** [comment]
If possible code example would be nice since there is no documentation on it.

**Comment by stirante** [comment]
The documentation is available through [rift-explorer](https://github.com/Pupix/rift-explorer). There you can also find what kind of POJO is returned, since all POJO are generated based on this documentation.

To get all rune pages player have:
```
LolPerksPerkPageResource[] pages = api.executeGet("/lol-perks/v1/pages", LolPerksPerkPageResource[].class).getResponseObject();
```

To add new rune page from the code:
```
LolPerksPerkPageResource page = new LolPerksPerkPageResource();
//Set stuff for the page
api.executePost("/lol-perks/v1/pages/", page);
```

**Comment by SimronJ** [comment]
Thank you for the help!

rift-explorer have an issue connecting to a new league client and there is no fix yet.

**Comment by stirante** [comment]
There is also a documentation available online, but lacks the response schema at [lcu.vivide.re](http://lcu.vivide.re/)

Also closing the issue, as rift-explorer issues aren't related to the library.
