### ISSUE TITLE
Reconnect logic?

### ISSUE THREAD

**Issue by sabihismail** [stirante/lol-client-java-api#25]
Hi,

Is there some way to auto-detect the league client being restarted/logging into another user? Or some alternative solution to enable this?

Thanks!

**Comment by stirante** [comment]
Hi,

The connection is listener based, so you can notice, that first you get `onClientDisconnected` and then `onClientConnected`. If you don't, you can always print all events from the websocket and check if there is some characteristic event sent on restart/relogin.
