### ISSUE TITLE
New Build with Thread Changes?

### ISSUE THREAD

**Issue by sabihismail** [stirante/lol-client-java-api#27]
Hi,

I'm having an issue where the SimpleConsole is not re-initialized on ClientApi re-creation. I saw with https://github.com/stirante/lol-client-java-api/commit/641f8b643792f1408dcb2b918ac82ab861176d77, this is fixed (setting it to null on api.stop() -> thread.close()).

When can we expect to see a new build?

If not soon, any suggestions for a workaround you may have?

Use case: Trying to re-initialize client API when the client is closed and then reopened, but there seems to be some issue where the API is unable to connect to the client after the first initialization.

Thanks

**Comment by sabihismail** [comment]
Sorry, will run more tests and reopen this issue when I get more information, I didn't realize I was on 1.2.3 not 1.2.5.

**Comment by stirante** [comment]
The latest commit is always built [here](https://jenkins.stirante.com/job/lol-client-java-api/)
You can use it by adding this repository to Maven:
```xml
        <repository>
            <id>stirante-nexus-snapshots</id>
            <url>https://nexus.stirante.com/repository/maven-snapshots/</url>
        </repository>
```
And this dependency:
```xml

        <dependency>
            <groupId>com.stirante</groupId>
            <artifactId>lol-client-java-api</artifactId>
            <version>1.2.5-SNAPSHOT</version>
        </dependency>
```

I admit, that I should make actual releases more frequently. I will make a release sometime this week.
