### ISSUE TITLE
Is there a way to know the params values?

### ISSUE THREAD

**Issue by Blaconix** [stirante/lol-client-java-api#3]
For example, there's this endpoint:
`POST /lol-simple-dialog-messages/v1/messages`

The data which needs to be sent is:
```
PARAM messageRequest:
{
  "msgBody": [
    "string"
  ],
  "msgType": "string"
}
```
It doesn't really matter what I fill those options with, the message is every time empty. Any ideas?
Maybe there are some specific params..

![image](https://user-images.githubusercontent.com/13063686/41821024-57d863e0-77e3-11e8-99ee-b45721bd0df3.png)

**Comment by stirante** [comment]
There isn't really a way for that except listening on the client web socket when this message happens on it's own. 
My best guess is that the msgBody requires key to translatable string just like `/player-notifications/v1/notifications` does and the other elements of this array are parameters for this string.

**Comment by Blaconix** [comment]
Ugh, key to translatable string. That means there's not really a way to use a custom message.
