### ISSUE TITLE
[QUESTION] Client Connection not working as expected

### ISSUE THREAD

**Issue by datschi23** [stirante/lol-client-java-api#30]
Hey, I tried to connect to the client API with this project. I created a Java project and added the dependencies in the pom.xml as described in the README. I then copied the code from the "SkinListExample.java" and ran it locally. The program starts, but I don't see any output in the console. When I debug the program, I see that after "api.addClientConnectionListener(new ClientConnectionListener() {" the program goes directly to the end and does not try to connect to the client. I have had the League Client open as written in the README. I also tried the other examples in the README, but without success

https://user-images.githubusercontent.com/64021184/170552963-5cebdc6b-fd35-4b19-a59e-eee30516c12e.mp4

.

**Comment by stirante** [comment]
Hey, are you using version 1.2.3 from readme, 1.2.5 latest release or 1.2.7-SNAPSHOT from my own repository?

Also it's supposed to go straight to the end of the code, because the client connection listener should be called async when the connection is available.

**Comment by datschi23** [comment]
I am using version 1.2.5

**Comment by datschi23** [comment]
This is the output:
[log.txt](https://github.com/stirante/lol-client-java-api/files/8782338/log.txt)

**Comment by stirante** [comment]
Looks like it hid the command line arguments from you for some reason. For me it returns something like this:
```
"C:/Riot Games/League of Legends/LeagueClientUx.exe" "--riotclient-auth-token=XXX" "--riotclient-app-port=21931" "--no-rads" "--disable-self-update" "--region=EUNE" "--locale=en_GB" "--remoting-auth-token=XXX" "--respawn-command=LeagueClient.exe" "--respawn-display-name=League of Legends" "--app-port=21991" "--install-directory=C:\Riot Games\League of Legends" "--app-name=LeagueClient" "--ux-name=LeagueClientUx" "--ux-helper-name=LeagueClientUxHelper" "--log-dir=LeagueClient Logs" "--crash-reporting=crashpad" "--crash-environment=EUN1" "--crash-pipe=\\.\pipe\crashpad_10800_LRQKEITGOWEJRQHR" "--app-log-file-path=C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2022-05-27T08-18-08_10800_LeagueClient.log" "--app-pid=10800" "--output-base-dir=C:\Riot Games\League of Legends" "--no-proxy-server"  
```

**Comment by datschi23** [comment]
Okay, I had to start Intellij as administrator to get it to work. This is the output:
[log.txt](https://github.com/stirante/lol-client-java-api/files/8785460/log.txt)

I tested the previous code with administrator rights and it worked now. Is it normal that I need administrator rights?

**Comment by stirante** [comment]
Sometimes it was caused by LoL being ran with administrator rights, but again not always. Seems like it depends on the OS most of the times.

**Comment by datschi23** [comment]
Okay, I will try to force the application to run with administrator. Thanks for the quick help.
