### ISSUE TITLE
Jitpack might be dead

### ISSUE THREAD

**Issue by sabihismail** [stirante/lol-client-java-api#31]
Not sure yet, but some are saying its abandoned.

Can't compile since I'm using -SNAPSHOT for your build, wondering if you know about this?

https://github.com/jitpack/jitpack.io/issues/5337

**Comment by stirante** [comment]
Thanks for the info. Does my own maven repository work?
Configuration: https://github.com/stirante/lol-client-java-api#snapshots

**Comment by sabihismail** [comment]
Yup it does! Thanks :)
