### ISSUE TITLE
How do you update the generated folder?

### ISSUE THREAD

**Issue by robinwithes** [stirante/lol-client-java-api#5]
It might be a good idea to share your method of updating the generated module so that other people can do it in case of your absence.

**Comment by stirante** [comment]
I added class I was using to generate those classes along with pretty easy way to run it in https://github.com/stirante/lol-client-java-api/commit/7f880d7abbd439e502eb14230caa6019ea2a5e37

Now if you want to generate those classes, just run LoL client with swagger enabled and run ```mvn clean compile exec:java``` in working directory of the project.
