### ISSUE TITLE
ERROR: Can't find league client

### ISSUE THREAD

**Issue by robinwithes** [stirante/lol-client-java-api#7]
So basically a few people (2 is know so far) have a different league client --install-directory= paramater value. Normally this is: `C:\something\LeagueOfLegends\` notice the \ at the end. But for these 2 people it is: `C:\something\LeagueOfLegends`.
Then when the api tries to get the lockfile using this location it doesn't find it since it tries to find `C:\something\LeagueOfLegendsLockfile` thus it gives a error.
The location where the exception is thrown is ClientApi.java

**Comment by stirante** [comment]
Should be fixed in 3e58dc8966a9c94fe5526b780cb27897a39cfc02
